/**
 * Frozen snapshot of the pre-W2.5 curated icon catalog (431 names, commit
 * 647eb97's `src/icons.ts`) — the compat-lock fixture for `catalog.test.ts`.
 * lucide renames icons upstream between releases (e.g. v1.24 → v1.25 folded
 * "home" into "house"), so `scripts/gen-pptx-icons.mts` must keep every one
 * of these names resolvable in the regenerated `PPTX_ICON_NAMES` — either it
 * is still lucide's current canonical name, or (when upstream dropped the
 * name outright) the script adds a manual entry for it in its own
 * `COMPAT_ALIASES` map. Do not edit this list: it is a historical snapshot,
 * not a target to keep updated as new icons are added.
 */
export const LEGACY_ICON_NAMES = [
  "info", "triangle-alert", "lightbulb", "check", "circle-check", "circle-x",
  "circle-alert", "trending-up", "trending-down", "activity", "chart-column", "chart-line",
  "chart-pie", "gauge", "server", "database", "hard-drive", "cpu",
  "cloud", "network", "globe", "layers", "package", "boxes",
  "shield", "shield-check", "lock", "key", "users", "user",
  "handshake", "target", "rocket", "flag", "zap", "wrench",
  "settings", "search", "git-branch", "refresh-cw", "clock", "calendar",
  "download", "upload", "link", "dollar-sign", "percent", "briefcase",
  "file-text", "folder", "monitor", "laptop", "smartphone", "terminal",
  "bug", "code", "workflow", "git-merge", "git-pull-request", "component",
  "blocks", "container", "cog", "puzzle", "list-checks", "clipboard-list",
  "clipboard-check", "book-open", "files", "archive", "file-check", "file-plus",
  "file-search", "inbox", "send", "list", "list-ordered", "table",
  "award", "trophy", "medal", "star", "heart", "thumbs-up",
  "crown", "badge-check", "bell", "megaphone", "mail", "message-square",
  "phone", "video", "camera", "mic", "share-2", "external-link",
  "qr-code", "hash", "at-sign", "wifi", "signal", "plug",
  "power", "sun", "moon", "flame", "droplets", "snowflake",
  "wind", "thermometer", "infinity", "map", "map-pin", "compass",
  "navigation", "route", "truck", "plane", "ship", "building",
  "building-2", "factory", "warehouse", "store", "home", "landmark",
  "banknote", "credit-card", "wallet", "coins", "piggy-bank", "receipt",
  "calculator", "scale", "timer", "hourglass", "alarm-clock", "history",
  "filter", "sliders-horizontal", "layout-grid", "eye", "play", "pause",
  "repeat", "undo-2", "redo-2", "maximize-2", "zoom-in", "user-check",
  "user-plus", "gift", "stethoscope", "pill", "syringe", "heart-pulse",
  "ambulance", "hospital", "dna", "brain", "bandage", "microscope",
  "graduation-cap", "school", "university", "library", "book", "flask-conical",
  "test-tube", "beaker", "atom", "telescope", "notebook", "pencil",
  "ruler", "brain-circuit", "bot", "sparkles", "binary", "braces",
  "regex", "variable", "sigma", "pi", "microchip", "memory-stick",
  "gpu", "circuit-board", "scan", "radar", "orbit", "satellite",
  "satellite-dish", "webhook", "waypoints", "chart-area", "chart-bar", "chart-scatter",
  "chart-spline", "chart-gantt", "chart-candlestick", "chart-network", "chart-no-axes-combined", "trending-up-down",
  "goal", "crosshair", "server-cog", "server-crash", "server-off", "database-backup",
  "database-search", "database-zap", "monitor-check", "monitor-cog", "ethernet-port", "router",
  "cable", "usb", "unplug", "hard-drive-download", "hard-drive-upload", "cloud-cog",
  "cloud-off", "cloud-upload", "cloud-download", "cloud-check", "cloud-alert", "wifi-off",
  "logs", "git-commit", "git-compare", "git-fork", "git-graph", "square-terminal",
  "bug-off", "shield-alert", "shield-x", "shield-off", "shield-plus", "lock-open",
  "key-round", "siren", "ban", "cctv", "fire-extinguisher", "door-closed",
  "door-open", "vault", "file-code", "file-json", "file-spreadsheet", "file-archive",
  "file-diff", "file-clock", "file-warning", "file-x", "file-down", "file-up",
  "file-stack", "folder-open", "folder-tree", "folder-cog", "folder-check", "save",
  "scroll-text", "sticky-note", "notepad-text", "newspaper", "signature", "stamp",
  "paperclip", "pin", "bookmark", "shopping-cart", "shopping-bag", "gem",
  "euro", "bitcoin", "japanese-yen", "currency", "badge-dollar-sign", "badge-percent",
  "gavel", "tag", "tags", "ticket", "barcode", "users-round",
  "user-cog", "user-search", "user-x", "user-minus", "id-card", "speech",
  "messages-square", "message-circle", "reply", "heart-handshake", "hand-helping", "hand-coins",
  "phone-call", "headset", "headphones", "presentation", "projector", "printer",
  "screen-share", "cast", "car", "bus", "train", "bike",
  "sailboat", "anchor", "fuel", "traffic-cone", "milestone", "signpost",
  "luggage", "helicopter", "forklift", "tractor", "drone", "package-check",
  "package-search", "package-open", "leaf", "sprout", "recycle", "solar-panel",
  "battery", "battery-charging", "ev-charger", "dam", "radiation", "mountain",
  "trees", "waves", "earth", "sunrise", "sunset", "cloud-rain",
  "cloud-snow", "cloud-lightning", "umbrella", "tornado", "coffee", "utensils",
  "chef-hat", "wheat", "apple", "dumbbell", "calendar-days", "calendar-clock",
  "calendar-check", "calendar-x", "calendar-range", "clock-alert", "watch", "layout-dashboard",
  "layout-list", "layout-template", "kanban", "columns-3", "rows-3", "grid-3x3",
  "list-todo", "list-tree", "list-filter", "eye-off", "focus", "locate-fixed",
  "minimize-2", "zoom-out", "mouse-pointer", "mouse-pointer-click", "keyboard", "mouse",
  "loader-circle", "shuffle", "merge", "split", "shapes", "box",
  "pyramid", "arrow-right", "arrow-left", "arrow-up", "arrow-down", "arrow-up-right",
  "arrow-down-right", "arrow-left-right", "arrow-up-down", "chevron-right", "chevrons-right", "corner-down-right",
  "iteration-cw", "rotate-cw", "rotate-ccw", "refresh-ccw", "expand", "shrink",
  "log-in", "log-out", "star-half", "thumbs-down", "smile", "frown",
  "meh", "party-popper", "ribbon", "hammer", "anvil", "drill",
  "pickaxe", "hard-hat", "construction", "magnet", "bolt", "paintbrush",
  "palette", "scissors", "flashlight", "life-buoy", "octagon-alert", "octagon-x",
  "badge-alert", "badge-info", "circle-help", "bell-ring", "bell-off",
] as const
